- hosts: isucon_servers
  become: true
  tasks:
    # Install unzip
    - name: Install unzip
      apt:
        name: unzip
        state: present
    # Install ALP (Access Log Profiler)
    - name: Download and install ALP
      shell: |
        wget https://github.com/tkuchiki/alp/releases/download/v1.0.11/alp_linux_amd64.zip
        unzip alp_linux_amd64.zip
        sudo install ./alp /usr/local/bin
      args:
        creates: /usr/local/bin/alp

    # Install pt-query-digest (Percona Toolkit)
    - name: Install Percona Toolkit
      shell: |
        wget https://github.com/percona/percona-toolkit/archive/refs/tags/v3.5.5.tar.gz
        tar zxvf v3.5.5.tar.gz
        ./percona-toolkit-3.5.5/bin/pt-query-digest --version
        sudo install ./percona-toolkit-3.5.5/bin/pt-query-digest /usr/local/bin
      args:
        creates: pt-query-digest
